@MarketPlaceApi_HostAddress = http://localhost:5177


GET {{MarketPlaceApi_HostAddress}}
Accept: application/json

###
POST {{MarketPlaceApi_HostAddress}}/api/v1/auth/login/email
Content-Type: application/json

{
    "email": "testu11se1r@gmail.com",
    "password": "Password@21123"
}

###
POST {{MarketPlaceApi_HostAddress}}/auth/login/verify-otp
Content-Type: application/json

{
  "otpId": "e1d6c991-e165-4d1f-933b-4d49986c51eb",
  "otpInput": "602980"
}
###
POST {{MarketPlaceApi_HostAddress}}/redis
Content-Type: application/json

{
  "name": "amaechi",
  "age": 34
}