@MarketPlaceApi_HostAddress = http://localhost:5177


GET {{MarketPlaceApi_HostAddress}}
Accept: application/json

###
POST {{MarketPlaceApi_HostAddress}}/users/register
Content-Type: application/json

{
    "email": "testuser@gmail.com",
    "password": "Password@21123"
}